const countriesTimeZones = [
  { country: 'Afghanistan', country_es: 'Afganistán', timeZone: 'Asia/Kabul' },
  { country: 'Albania', country_es: 'Albania', timeZone: 'Europe/Tirane' },
  { country: 'Algeria', country_es: 'Argelia', timeZone: 'Africa/Algiers' },
  { country: 'Andorra', country_es: 'Andorra', timeZone: 'Europe/Andorra' },
  { country: 'Angola', country_es: 'Angola', timeZone: 'Africa/Luanda' },
  { country: 'Antigua and Barbuda', country_es: 'Antigua y Barbuda', timeZone: 'America/Antigua' },
  { country: 'Argentina', country_es: 'Argentina', timeZone: 'America/Argentina/Buenos_Aires' },
  { country: 'Armenia', country_es: 'Armenia', timeZone: 'Asia/Yerevan' },
  { country: 'Australia', country_es: 'Australia', timeZone: 'Australia/Sydney' },
  { country: 'Austria', country_es: 'Austria', timeZone: 'Europe/Vienna' },
  { country: 'Azerbaijan', country_es: 'Azerbaiyán', timeZone: 'Asia/Baku' },
  { country: 'Bahamas', country_es: 'Bahamas', timeZone: 'America/Nassau' },
  { country: 'Bahrain', country_es: 'Baréin', timeZone: 'Asia/Bahrain' },
  { country: 'Bangladesh', country_es: 'Bangladés', timeZone: 'Asia/Dhaka' },
  { country: 'Barbados', country_es: 'Barbados', timeZone: 'America/Barbados' },
  { country: 'Belarus', country_es: 'Bielorrusia', timeZone: 'Europe/Minsk' },
  { country: 'Belgium', country_es: 'Bélgica', timeZone: 'Europe/Brussels' },
  { country: 'Belize', country_es: 'Belice', timeZone: 'America/Belize' },
  { country: 'Benin', country_es: 'Benín', timeZone: 'Africa/Porto-Novo' },
  { country: 'Bhutan', country_es: 'Bután', timeZone: 'Asia/Thimphu' },
  { country: 'Bolivia', country_es: 'Bolivia', timeZone: 'America/La_Paz' },
  { country: 'Bosnia and Herzegovina', country_es: 'Bosnia y Herzegovina', timeZone: 'Europe/Sarajevo' },
  { country: 'Botswana', country_es: 'Botsuana', timeZone: 'Africa/Gaborone' },
  { country: 'Brazil', country_es: 'Brasil', timeZone: 'America/Sao_Paulo' },
  { country: 'Brunei', country_es: 'Brunéi', timeZone: 'Asia/Brunei' },
  { country: 'Bulgaria', country_es: 'Bulgaria', timeZone: 'Europe/Sofia' },
  { country: 'Burkina Faso', country_es: 'Burkina Faso', timeZone: 'Africa/Ouagadougou' },
  { country: 'Burundi', country_es: 'Burundi', timeZone: 'Africa/Bujumbura' },
  { country: 'Cabo Verde', country_es: 'Cabo Verde', timeZone: 'Atlantic/Cape_Verde' },
  { country: 'Cambodia', country_es: 'Camboya', timeZone: 'Asia/Phnom_Penh' },
  { country: 'Cameroon', country_es: 'Camerún', timeZone: 'Africa/Douala' },
  { country: 'Canada', country_es: 'Canadá', timeZone: 'America/Toronto' },
  { country: 'Central African Republic', country_es: 'República Centroafricana', timeZone: 'Africa/Bangui' },
  { country: 'Chad', country_es: 'Chad', timeZone: 'Africa/Ndjamena' },
  { country: 'Chile', country_es: 'Chile', timeZone: 'America/Santiago' },
  { country: 'China', country_es: 'China', timeZone: 'Asia/Shanghai' },
  { country: 'Colombia', country_es: 'Colombia', timeZone: 'America/Bogota' },
  { country: 'Comoros', country_es: 'Comoras', timeZone: 'Indian/Comoro' },
  { country: 'Congo', country_es: 'Congo', timeZone: 'Africa/Brazzaville' },
  { country: 'Costa Rica', country_es: 'Costa Rica', timeZone: 'America/Costa_Rica' },
  { country: 'Croatia', country_es: 'Croacia', timeZone: 'Europe/Zagreb' },
  { country: 'Cuba', country_es: 'Cuba', timeZone: 'America/Havana' },
  { country: 'Cyprus', country_es: 'Chipre', timeZone: 'Asia/Nicosia' },
  { country: 'Czech Republic', country_es: 'República Checa', timeZone: 'Europe/Prague' },
  { country: 'Denmark', country_es: 'Dinamarca', timeZone: 'Europe/Copenhagen' },
  { country: 'Djibouti', country_es: 'Yibuti', timeZone: 'Africa/Djibouti' },
  { country: 'Dominica', country_es: 'Dominica', timeZone: 'America/Dominica' },
  { country: 'Dominican Republic', country_es: 'República Dominicana', timeZone: 'America/Santo_Domingo' },
  { country: 'Ecuador', country_es: 'Ecuador', timeZone: 'America/Guayaquil' },
  { country: 'Egypt', country_es: 'Egipto', timeZone: 'Africa/Cairo' },
  { country: 'El Salvador', country_es: 'El Salvador', timeZone: 'America/El_Salvador' },
  { country: 'Equatorial Guinea', country_es: 'Guinea Ecuatorial', timeZone: 'Africa/Malabo' },
  { country: 'Eritrea', country_es: 'Eritrea', timeZone: 'Africa/Asmara' },
  { country: 'Estonia', country_es: 'Estonia', timeZone: 'Europe/Tallinn' },
  { country: 'Eswatini', country_es: 'Esuatini', timeZone: 'Africa/Mbabane' },
  { country: 'Ethiopia', country_es: 'Etiopía', timeZone: 'Africa/Addis_Ababa' },
  { country: 'Fiji', country_es: 'Fiyi', timeZone: 'Pacific/Fiji' },
  { country: 'Finland', country_es: 'Finlandia', timeZone: 'Europe/Helsinki' },
  { country: 'France', country_es: 'Francia', timeZone: 'Europe/Paris' },
  { country: 'Gabon', country_es: 'Gabón', timeZone: 'Africa/Libreville' },
  { country: 'Gambia', country_es: 'Gambia', timeZone: 'Africa/Banjul' },
  { country: 'Georgia', country_es: 'Georgia', timeZone: 'Asia/Tbilisi' },
  { country: 'Germany', country_es: 'Alemania', timeZone: 'Europe/Berlin' },
  { country: 'Ghana', country_es: 'Ghana', timeZone: 'Africa/Accra' },
  { country: 'Greece', country_es: 'Grecia', timeZone: 'Europe/Athens' },
  { country: 'Grenada', country_es: 'Granada', timeZone: 'America/Grenada' },
  { country: 'Guatemala', country_es: 'Guatemala', timeZone: 'America/Guatemala' },
  { country: 'Guinea', country_es: 'Guinea', timeZone: 'Africa/Conakry' },
  { country: 'Guinea-Bissau', country_es: 'Guinea-Bisáu', timeZone: 'Africa/Bissau' },
  { country: 'Guyana', country_es: 'Guyana', timeZone: 'America/Guyana' },
  { country: 'Haiti', country_es: 'Haití', timeZone: 'America/Port-au-Prince' },
  { country: 'Honduras', country_es: 'Honduras', timeZone: 'America/Tegucigalpa' },
  { country: 'Hungary', country_es: 'Hungría', timeZone: 'Europe/Budapest' },
  { country: 'Iceland', country_es: 'Islandia', timeZone: 'Atlantic/Reykjavik' },
  { country: 'India', country_es: 'India', timeZone: 'Asia/Kolkata' },
  { country: 'Indonesia', country_es: 'Indonesia', timeZone: 'Asia/Jakarta' },
  { country: 'Iran', country_es: 'Irán', timeZone: 'Asia/Tehran' },
  { country: 'Iraq', country_es: 'Irak', timeZone: 'Asia/Baghdad' },
  { country: 'Ireland', country_es: 'Irlanda', timeZone: 'Europe/Dublin' },
  { country: 'Israel', country_es: 'Israel', timeZone: 'Asia/Jerusalem' },
  { country: 'Italy', country_es: 'Italia', timeZone: 'Europe/Rome' },
  { country: 'Ivory Coast', country_es: 'Costa de Marfil', timeZone: 'Africa/Abidjan' },
  { country: 'Jamaica', country_es: 'Jamaica', timeZone: 'America/Jamaica' },
  { country: 'Japan', country_es: 'Japón', timeZone: 'Asia/Tokyo' },
  { country: 'Jordan', country_es: 'Jordania', timeZone: 'Asia/Amman' },
  { country: 'Kazakhstan', country_es: 'Kazajistán', timeZone: 'Asia/Almaty' },
  { country: 'Kenya', country_es: 'Kenia', timeZone: 'Africa/Nairobi' },
  { country: 'Kiribati', country_es: 'Kiribati', timeZone: 'Pacific/Tarawa' },
  { country: 'Kuwait', country_es: 'Kuwait', timeZone: 'Asia/Kuwait' },
  { country: 'Kyrgyzstan', country_es: 'Kirguistán', timeZone: 'Asia/Bishkek' },
  { country: 'Laos', country_es: 'Laos', timeZone: 'Asia/Vientiane' },
  { country: 'Latvia', country_es: 'Letonia', timeZone: 'Europe/Riga' },
  { country: 'Lebanon', country_es: 'Líbano', timeZone: 'Asia/Beirut' },
  { country: 'Lesotho', country_es: 'Lesoto', timeZone: 'Africa/Maseru' },
  { country: 'Liberia', country_es: 'Liberia', timeZone: 'Africa/Monrovia' },
  { country: 'Libya', country_es: 'Libia', timeZone: 'Africa/Tripoli' },
  { country: 'Liechtenstein', country_es: 'Liechtenstein', timeZone: 'Europe/Vaduz' },
  { country: 'Lithuania', country_es: 'Lituania', timeZone: 'Europe/Vilnius' },
  { country: 'Luxembourg', country_es: 'Luxemburgo', timeZone: 'Europe/Luxembourg' },
  { country: 'Madagascar', country_es: 'Madagascar', timeZone: 'Indian/Antananarivo' },
  { country: 'Malawi', country_es: 'Malaui', timeZone: 'Africa/Blantyre' },
  { country: 'Malaysia', country_es: 'Malasia', timeZone: 'Asia/Kuala_Lumpur' },
  { country: 'Maldives', country_es: 'Maldivas', timeZone: 'Indian/Maldives' },
  { country: 'Mali', country_es: 'Malí', timeZone: 'Africa/Bamako' },
  { country: 'Malta', country_es: 'Malta', timeZone: 'Europe/Malta' },
  { country: 'Marshall Islands', country_es: 'Islas Marshall', timeZone: 'Pacific/Majuro' },
  { country: 'Mauritania', country_es: 'Mauritania', timeZone: 'Africa/Nouakchott' },
  { country: 'Mauritius', country_es: 'Mauricio', timeZone: 'Indian/Mauritius' },
  { country: 'Mexico', country_es: 'México', timeZone: 'America/Mexico_City' },
  { country: 'Micronesia', country_es: 'Micronesia', timeZone: 'Pacific/Pohnpei' },
  { country: 'Moldova', country_es: 'Moldavia', timeZone: 'Europe/Chisinau' },
  { country: 'Monaco', country_es: 'Mónaco', timeZone: 'Europe/Monaco' },
  { country: 'Mongolia', country_es: 'Mongolia', timeZone: 'Asia/Ulaanbaatar' },
  { country: 'Montenegro', country_es: 'Montenegro', timeZone: 'Europe/Podgorica' },
  { country: 'Morocco', country_es: 'Marruecos', timeZone: 'Africa/Casablanca' },
  { country: 'Mozambique', country_es: 'Mozambique', timeZone: 'Africa/Maputo' },
  { country: 'Myanmar', country_es: 'Birmania', timeZone: 'Asia/Yangon' },
  { country: 'Namibia', country_es: 'Namibia', timeZone: 'Africa/Windhoek' },
  { country: 'Nauru', country_es: 'Nauru', timeZone: 'Pacific/Nauru' },
  { country: 'Nepal', country_es: 'Nepal', timeZone: 'Asia/Kathmandu' },
  { country: 'Netherlands', country_es: 'Países Bajos', timeZone: 'Europe/Amsterdam' },
  { country: 'New Zealand', country_es: 'Nueva Zelanda', timeZone: 'Pacific/Auckland' },
  { country: 'Nicaragua', country_es: 'Nicaragua', timeZone: 'America/Managua' },
  { country: 'Niger', country_es: 'Níger', timeZone: 'Africa/Niamey' },
  { country: 'Nigeria', country_es: 'Nigeria', timeZone: 'Africa/Lagos' },
  { country: 'North Macedonia', country_es: 'Macedonia del Norte', timeZone: 'Europe/Skopje' },
  { country: 'Norway', country_es: 'Noruega', timeZone: 'Europe/Oslo' },
  { country: 'Oman', country_es: 'Omán', timeZone: 'Asia/Muscat' },
  { country: 'Pakistan', country_es: 'Pakistán', timeZone: 'Asia/Karachi' },
  { country: 'Palau', country_es: 'Palaos', timeZone: 'Pacific/Palau' },
  { country: 'Palestine', country_es: 'Palestina', timeZone: 'Asia/Gaza' },
  { country: 'Panama', country_es: 'Panamá', timeZone: 'America/Panama' },
  { country: 'Papua New Guinea', country_es: 'Papúa Nueva Guinea', timeZone: 'Pacific/Port_Moresby' },
  { country: 'Paraguay', country_es: 'Paraguay', timeZone: 'America/Asuncion' },
  { country: 'Peru', country_es: 'Perú', timeZone: 'America/Lima' },
  { country: 'Philippines', country_es: 'Filipinas', timeZone: 'Asia/Manila' },
  { country: 'Poland', country_es: 'Polonia', timeZone: 'Europe/Warsaw' },
  { country: 'Portugal', country_es: 'Portugal', timeZone: 'Europe/Lisbon' },
  { country: 'Qatar', country_es: 'Catar', timeZone: 'Asia/Qatar' },
  { country: 'Romania', country_es: 'Rumania', timeZone: 'Europe/Bucharest' },
  { country: 'Russia', country_es: 'Rusia', timeZone: 'Europe/Moscow' },
  { country: 'Rwanda', country_es: 'Ruanda', timeZone: 'Africa/Kigali' },
  { country: 'Saint Kitts and Nevis', country_es: 'San Cristóbal y Nieves', timeZone: 'America/St_Kitts' },
  { country: 'Saint Lucia', country_es: 'Santa Lucía', timeZone: 'America/St_Lucia' },
  {
    country: 'Saint Vincent and the Grenadines',
    country_es: 'San Vicente y las Granadinas',
    timeZone: 'America/St_Vincent',
  },
  { country: 'Samoa', country_es: 'Samoa', timeZone: 'Pacific/Apia' },
  { country: 'San Marino', country_es: 'San Marino', timeZone: 'Europe/San_Marino' },
  { country: 'Sao Tome and Principe', country_es: 'Santo Tomé y Príncipe', timeZone: 'Africa/Sao_Tome' },
  { country: 'Saudi Arabia', country_es: 'Arabia Saudita', timeZone: 'Asia/Riyadh' },
  { country: 'Senegal', country_es: 'Senegal', timeZone: 'Africa/Dakar' },
  { country: 'Serbia', country_es: 'Serbia', timeZone: 'Europe/Belgrade' },
  { country: 'Seychelles', country_es: 'Seychelles', timeZone: 'Indian/Mahe' },
  { country: 'Sierra Leone', country_es: 'Sierra Leona', timeZone: 'Africa/Freetown' },
  { country: 'Singapore', country_es: 'Singapur', timeZone: 'Asia/Singapore' },
  { country: 'Slovakia', country_es: 'Eslovaquia', timeZone: 'Europe/Bratislava' },
  { country: 'Slovenia', country_es: 'Eslovenia', timeZone: 'Europe/Ljubljana' },
  { country: 'Solomon Islands', country_es: 'Islas Salomón', timeZone: 'Pacific/Guadalcanal' },
  { country: 'Somalia', country_es: 'Somalia', timeZone: 'Africa/Mogadishu' },
  { country: 'South Africa', country_es: 'Sudáfrica', timeZone: 'Africa/Johannesburg' },
  { country: 'South Korea', country_es: 'Corea del Sur', timeZone: 'Asia/Seoul' },
  { country: 'South Sudan', country_es: 'Sudán del Sur', timeZone: 'Africa/Juba' },
  { country: 'Spain', country_es: 'España', timeZone: 'Europe/Madrid' },
  { country: 'Sri Lanka', country_es: 'Sri Lanka', timeZone: 'Asia/Colombo' },
  { country: 'Sudan', country_es: 'Sudán', timeZone: 'Africa/Khartoum' },
  { country: 'Suriname', country_es: 'Surinam', timeZone: 'America/Paramaribo' },
  { country: 'Sweden', country_es: 'Suecia', timeZone: 'Europe/Stockholm' },
  { country: 'Switzerland', country_es: 'Suiza', timeZone: 'Europe/Zurich' },
  { country: 'Syria', country_es: 'Siria', timeZone: 'Asia/Damascus' },
  { country: 'Taiwan', country_es: 'Taiwán', timeZone: 'Asia/Taipei' },
  { country: 'Tajikistan', country_es: 'Tayikistán', timeZone: 'Asia/Dushanbe' },
  { country: 'Tanzania', country_es: 'Tanzania', timeZone: 'Africa/Dar_es_Salaam' },
  { country: 'Thailand', country_es: 'Tailandia', timeZone: 'Asia/Bangkok' },
  { country: 'Timor-Leste', country_es: 'Timor Oriental', timeZone: 'Asia/Dili' },
  { country: 'Togo', country_es: 'Togo', timeZone: 'Africa/Lome' },
  { country: 'Tonga', country_es: 'Tonga', timeZone: 'Pacific/Tongatapu' },
  { country: 'Trinidad and Tobago', country_es: 'Trinidad y Tobago', timeZone: 'America/Port_of_Spain' },
  { country: 'Tunisia', country_es: 'Túnez', timeZone: 'Africa/Tunis' },
  { country: 'Turkey', country_es: 'Turquía', timeZone: 'Europe/Istanbul' },
  { country: 'Turkmenistan', country_es: 'Turkmenistán', timeZone: 'Asia/Ashgabat' },
  { country: 'Tuvalu', country_es: 'Tuvalu', timeZone: 'Pacific/Funafuti' },
  { country: 'Uganda', country_es: 'Uganda', timeZone: 'Africa/Kampala' },
  { country: 'Ukraine', country_es: 'Ucrania', timeZone: 'Europe/Kiev' },
  { country: 'United Arab Emirates', country_es: 'Emiratos Árabes Unidos', timeZone: 'Asia/Dubai' },
  { country: 'United Kingdom', country_es: 'Reino Unido', timeZone: 'Europe/London' },
  { country: 'United States', country_es: 'Estados Unidos', timeZone: 'America/New_York' },
  { country: 'Uruguay', country_es: 'Uruguay', timeZone: 'America/Montevideo' },
  { country: 'Uzbekistan', country_es: 'Uzbekistán', timeZone: 'Asia/Tashkent' },
  { country: 'Vanuatu', country_es: 'Vanuatu', timeZone: 'Pacific/Efate' },
  { country: 'Vatican', country_es: 'Vaticano', timeZone: 'Europe/Vatican' },
  { country: 'Venezuela', country_es: 'Venezuela', timeZone: 'America/Caracas' },
  { country: 'Vietnam', country_es: 'Vietnam', timeZone: 'Asia/Ho_Chi_Minh' },
  { country: 'Yemen', country_es: 'Yemen', timeZone: 'Asia/Aden' },
  { country: 'Zambia', country_es: 'Zambia', timeZone: 'Africa/Lusaka' },
  { country: 'Zimbabwe', country_es: 'Zimbabue', timeZone: 'Africa/Harare' },
];

export function getCountryTimeZone(countryName: string) {
  const country = countriesTimeZones.find(({ country, country_es }) => {
    countryName = countryName.toLowerCase();
    if ([country.toLowerCase(), country_es.toLowerCase()].includes(countryName)) {
      return country;
    }
  });

  if (!country) return null;

  return country.timeZone;
}
